version: '3.3'

volumes:
  ulcccore:

networks:
  internal:

services:

  ulcccore: 
    build: 
      context: .
      args:
         APP_WORKDIR: ${APP_WORKDIR}
         BRANCH: ${BRANCH}
         APACHE_RUN_USER: ${APACHE_RUN_USER}
         APACHE_RUN_GROUP: ${APACHE_RUN_GROUP}
    env_file:
      - .env
    volumes:
      - ulcccore:$APP_WORKDIR/archives
    networks:
      internal:
    expose: 
      - 8080
    ports:
      - 80:8080