version: '3.3'

volumes:
  ulcccore:

networks:
  internal:

services:

  ulcccore: 
    build: 
      context: .
      args:
         BRANCH: ${BRANCH}
    env_file:
      - .env
    networks:
      internal:
    expose: 
      - 80
    ports:
      - 80:80