version: '3.3'

volumes:
  data:
  mariadb:

networks:
  internal:

services:
  # https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${APP_KEY}
      - MYSQL_USER=${APP_KEY}
    healthcheck:
      test: ["CMD-SHELL", 'mysqlshow -h mariadb -u $APP_KEY -p$MYSQL_PASSWORD $APP_KEY']
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      internal:
    deploy:
      endpoint_mode: dnsrr

  archives: 
    entrypoint: 
      - /bin/docker-entrypoint.sh
    build: 
      context: .
      args:
        APP_KEY: ${APP_KEY}
        APP_SOURCE: ${APP_SOURCE}
        EXTERNAL_HOSTNAME: ${EXTERNAL_HOSTNAME}
        SSH_PRIVATE_KEY_PATH: ${SSH_PRIVATE_KEY_PATH}
    env_file:
      - .env
    volumes:
      - data:$APP_WORKDIR/archives/${APP_KEY}/documents
    networks:
      internal:
    depends_on:
      - mariadb
    expose: 
      - 80
    ports:
      - 80:80
