version: '3.3'

volumes:
  mariadb:
  data:
  documents:
  letsencrypt:

networks:
  internal:

services:
  # https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", 'mysqlshow -h mariadb -u $APP_KEY -p$MYSQL_PASSWORD $APP_KEY']
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      internal:
    deploy:
      endpoint_mode: dnsrr

  archives: 
    entrypoint: 
      - /bin/docker-entrypoint.sh
    build: 
      context: .
      args:
        APP_KEY: ${APP_KEY}
        APP_SOURCE: ${APP_SOURCE}
        EXTERNAL_HOSTNAME: ${EXTERNAL_HOSTNAME}
        SSH_PRIVATE_KEY_PATH: ${SSH_PRIVATE_KEY_PATH}
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env
    volumes:
      - data:/data
      - documents:/opt/eprints3/archives/${APP_KEY}/documents
      - letsencrypt:/etc/letsencrypt
    networks:
      internal:
    depends_on:
      - mariadb
    expose: 
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
